services:
  db:
    image: postgres:15-alpine
    container_name: shorturl-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: person_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shorturl-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  migrate:
    image: migrate/migrate
    container_name: shorturl-migrate
    depends_on:
      - db
    volumes:
      - ./internal/storage/database/migrations:/migrations
    entrypoint: [ "migrate", "-path", "/migrations", "-database", "postgres://postgres:admin@db:5432/person_db?sslmode=disable", "up" ]

volumes:
  db_data:

